// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/aaronchen2k/deeptest/issues",
            "email": "462626@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/init/initdb": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "初始化项目",
                "parameters": [
                    {
                        "description": "初始化db",
                        "name": "ProjectReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serverDomain.DataReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/_domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/projects": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "项目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "enabled",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/_domain.PageData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "result": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/model.Project"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "更新项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "update project Request Object",
                        "name": "ProjectReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serverDomain.ProjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/_domain.Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "创建项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Create project Request Object",
                        "name": "ProjectReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serverDomain.ProjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/projects/apply": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "申请项目成员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "申请项目成员的请求体",
                        "name": "ApplyProjectReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serverDomain.ApplyProjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/_domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/audit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "审批操作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "审批操作的请求体",
                        "name": "AuditProjectReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serverDomain.AuditProjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/_domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/auditList": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "申请加入审批列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "申请加入审批列表的请求体",
                        "name": "AuditProjectPaginate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serverDomain.AuditProjectPaginate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/_domain.PageData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "result": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/model.ProjectMemberAudit"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/projects/changeProject": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "切换用户默认项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "项目ID",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/projects/changeUserRole": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "更新项目成员的角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "更新项目成员角色的请求体",
                        "name": "UpdateProjectMemberReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serverDomain.UpdateProjectMemberReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/_domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/getByUser": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "获取用户参与的项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                " currProject": {
                                                    "$ref": "#/definitions/model.Project"
                                                },
                                                " recentProjects": {
                                                    "type": "array",
                                                    "items": {
                                                        "$ref": "#/definitions/model.Project"
                                                    }
                                                },
                                                "projects": {
                                                    "type": "array",
                                                    "items": {
                                                        "$ref": "#/definitions/model.ProjectMemberRole"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/projects/members": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "获取项目成员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "enabled",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/_domain.PageData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "result": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/serverDomain.MemberResp"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/projects/removeMember": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "删除项目成员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "删除项目成员的请求体",
                        "name": "ProjectMemberRemoveReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serverDomain.ProjectMemberRemoveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/_domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "项目详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Project"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前项目ID",
                        "name": "currProjectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/_domain.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "_domain.PageData": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "result": {},
                "total": {
                    "type": "integer"
                }
            }
        },
        "_domain.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "consts.AuditStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "Init",
                "Agreed",
                "Refused"
            ]
        },
        "consts.RoleType": {
            "type": "string",
            "enum": [
                "admin",
                "user",
                "tester",
                "developer",
                "product_manager"
            ],
            "x-enum-varnames": [
                "Admin",
                "User",
                "Tester",
                "Developer",
                "ProductManager"
            ]
        },
        "model.Project": {
            "type": "object",
            "properties": {
                "adminId": {
                    "type": "integer"
                },
                "adminName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "environmentId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "includeExample": {
                    "type": "boolean"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orgId": {
                    "type": "integer"
                },
                "schemaId": {
                    "type": "integer"
                },
                "shortName": {
                    "type": "string"
                },
                "spec": {
                    "type": "string"
                },
                "spec2": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/serverConsts.ProjectType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ProjectMemberAudit": {
            "type": "object",
            "properties": {
                "applyUserId": {
                    "type": "integer"
                },
                "applyUserName": {
                    "type": "string"
                },
                "auditUserId": {
                    "type": "integer"
                },
                "auditUserName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "projectId": {
                    "type": "integer"
                },
                "projectName": {
                    "type": "string"
                },
                "projectRoleName": {
                    "$ref": "#/definitions/consts.RoleType"
                },
                "status": {
                    "$ref": "#/definitions/consts.AuditStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ProjectMemberRole": {
            "type": "object",
            "properties": {
                "adminId": {
                    "type": "integer"
                },
                "adminName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "environmentId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "includeExample": {
                    "type": "boolean"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orgId": {
                    "type": "integer"
                },
                "roleId": {
                    "type": "integer"
                },
                "roleName": {
                    "$ref": "#/definitions/consts.RoleType"
                },
                "schemaId": {
                    "type": "integer"
                },
                "shortName": {
                    "type": "string"
                },
                "spec": {
                    "type": "string"
                },
                "spec2": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/serverConsts.ProjectType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "serverConsts.ProjectType": {
            "type": "string",
            "enum": [
                "full",
                "debug"
            ],
            "x-enum-varnames": [
                "Full",
                "Debug"
            ]
        },
        "serverDomain.ApplyProjectReq": {
            "type": "object",
            "required": [
                "projectId",
                "projectRoleName"
            ],
            "properties": {
                "applyUserId": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "projectId": {
                    "type": "integer"
                },
                "projectRoleName": {
                    "$ref": "#/definitions/consts.RoleType"
                }
            }
        },
        "serverDomain.AuditProjectPaginate": {
            "type": "object",
            "properties": {
                "applyUserId": {
                    "type": "integer"
                },
                "auditUserId": {
                    "type": "integer"
                },
                "field": {
                    "type": "string"
                },
                "order": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "serverDomain.AuditProjectReq": {
            "type": "object",
            "required": [
                "id",
                "status"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/consts.AuditStatus"
                }
            }
        },
        "serverDomain.DataReq": {
            "type": "object",
            "properties": {
                "clearData": {
                    "type": "boolean"
                },
                "sys": {
                    "$ref": "#/definitions/serverDomain.DataSys"
                }
            }
        },
        "serverDomain.DataSys": {
            "type": "object",
            "properties": {
                "adminPassword": {
                    "type": "string"
                }
            }
        },
        "serverDomain.MemberResp": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "roleId": {
                    "type": "integer"
                },
                "roleName": {
                    "$ref": "#/definitions/consts.RoleType"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "serverDomain.ProjectMemberRemoveReq": {
            "type": "object",
            "properties": {
                "projectId": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "serverDomain.ProjectReq": {
            "type": "object",
            "properties": {
                "adminId": {
                    "type": "integer"
                },
                "adminName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "includeExample": {
                    "type": "boolean"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orgId": {
                    "type": "integer"
                },
                "schemaId": {
                    "type": "integer"
                },
                "shortName": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/serverConsts.ProjectType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "serverDomain.UpdateProjectMemberReq": {
            "type": "object",
            "properties": {
                "projectId": {
                    "type": "integer"
                },
                "projectRoleId": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "DeepTest服务端API文档",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
